name: docx_imagens
description: "Organizador de imagens docx."

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fluent_ui: ^4.8.7
  file_picker: ^8.0.5
  system_theme: ^3.0.0
  window_manager: ^0.4.2
  flutter_layout_grid: ^2.0.7
  docx_template: ^0.4.0
  path_provider: ^2.1.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  msix: ^3.16.8


flutter:
  uses-material-design: true
  assets:
    - lib/assets/template2x2.docx
    - lib/assets/template3x3.docx

msix_config:
  display_name: Docx Imagens
  publisher_display_name: Ocotea
  msix_version: 1.0.0.0
